const commands = [
            // System commands (100)
            {id: 1, name: "uname -a", description: "Display system information", category: "system"},
            {id: 2, name: "df -h", description: "Show disk space usage in human-readable format", category: "system"},
            {id: 3, name: "free -m", description: "Show memory usage in megabytes", category: "system"},
            {id: 4, name: "top", description: "Display dynamic real-time view of running processes", category: "system"},
            {id: 5, name: "htop", description: "Interactive process viewer (install with pkg first)", category: "system"},
            {id: 6, name: "ps aux", description: "Show all running processes with details", category: "system"},
            {id: 7, name: "kill [pid]", description: "Terminate process by process ID", category: "system"},
            {id: 8, name: "killall [process]", description: "Terminate all processes by name", category: "system"},
            {id: 9, name: "pkill [pattern]", description: "Kill processes by name pattern", category: "system"},
            {id: 10, name: "nice [command]", description: "Run command with modified scheduling priority", category: "system"},
            {id: 11, name: "renice [priority] [pid]", description: "Change priority of running process", category: "system"},
            {id: 12, name: "uptime", description: "Show how long system has been running", category: "system"},
            {id: 13, name: "w", description: "Show who is logged on and what they're doing", category: "system"},
            {id: 14, name: "who", description: "Show who is logged on", category: "system"},
            {id: 15, name: "whoami", description: "Print effective userid", category: "system"},
            {id: 16, name: "id", description: "Print user and group information", category: "system"},
            {id: 17, name: "last", description: "Show listing of last logged in users", category: "system"},
            {id: 18, name: "lastlog", description: "Reports the most recent login of all users", category: "system"},
            {id: 19, name: "date", description: "Display or set the system date and time", category: "system"},
            {id: 20, name: "cal", description: "Display a calendar", category: "system"},
            {id: 21, name: "timedatectl", description: "Control the system time and date (systemd)", category: "system"},
            {id: 22, name: "hwclock", description: "Query or set the hardware clock", category: "system"},
            {id: 23, name: "tzselect", description: "Select timezone interactively", category: "system"},
            {id: 24, name: "hostname", description: "Show or set the system's host name", category: "system"},
            {id: 25, name: "hostnamectl", description: "Control the system hostname (systemd)", category: "system"},
            {id: 26, name: "uname -r", description: "Display kernel release information", category: "system"},
            {id: 27, name: "uname -m", description: "Display machine hardware name", category: "system"},
            {id: 28, name: "arch", description: "Display machine hardware name (same as uname -m)", category: "system"},
            {id: 29, name: "lscpu", description: "Display information about the CPU architecture", category: "system"},
            {id: 30, name: "lshw", description: "List hardware configuration", category: "system"},
            {id: 31, name: "lsblk", description: "List block devices", category: "system"},
            {id: 32, name: "lsusb", description: "List USB devices", category: "system"},
            {id: 33, name: "lspci", description: "List PCI devices", category: "system"},
            {id: 34, name: "dmidecode", description: "DMI table decoder", category: "system"},
            {id: 35, name: "hdparm [device]", description: "Get/set SATA/IDE device parameters", category: "system"},
            {id: 36, name: "smartctl [device]", description: "Control and monitor SMART disks", category: "system"},
            {id: 37, name: "fdisk -l", description: "List disk partitions and sizes", category: "system"},
            {id: 38, name: "parted -l", description: "List disk partitions with details", category: "system"},
            {id: 39, name: "blkid", description: "Locate/print block device attributes", category: "system"},
            {id: 40, name: "lsmod", description: "Show the status of loaded kernel modules", category: "system"},
            {id: 41, name: "modinfo [module]", description: "Show information about a kernel module", category: "system"},
            {id: 42, name: "modprobe [module]", description: "Add or remove modules from the Linux kernel", category: "system"},
            {id: 43, name: "depmod", description: "Generate modules.dep and map files", category: "system"},
            {id: 44, name: "dmesg", description: "Print or control the kernel ring buffer", category: "system"},
            {id: 45, name: "journalctl", description: "Query the systemd journal", category: "system"},
            {id: 46, name: "logrotate", description: "Rotates, compresses, and mails system logs", category: "system"},
            {id: 47, name: "sysctl -a", description: "View all kernel parameters", category: "system"},
            {id: 48, name: "sysctl [parameter]", description: "View or modify kernel parameters at runtime", category: "system"},
            {id: 49, name: "ulimit -a", description: "Display all resource limits", category: "system"},
            {id: 50, name: "mount", description: "Mount a filesystem", category: "system"},
            {id: 51, name: "umount", description: "Unmount a filesystem", category: "system"},
            {id: 52, name: "findmnt", description: "Find a filesystem", category: "system"},
            {id: 53, name: "mount -t tmpfs tmpfs /mnt", description: "Mount a temporary filesystem", category: "system"},
            {id: 54, name: "swapon -s", description: "Show swap usage summary", category: "system"},
            {id: 55, name: "swapon [file]", description: "Enable swapping on file/device", category: "system"},
            {id: 56, name: "swapoff [file]", description: "Disable swapping on file/device", category: "system"},
            {id: 57, name: "mkswap [device]", description: "Set up a Linux swap area", category: "system"},
            {id: 58, name: "mkfs.ext4 [device]", description: "Create an ext4 filesystem", category: "system"},
            {id: 59, name: "fsck [device]", description: "Check and repair a Linux filesystem", category: "system"},
            {id: 60, name: "tune2fs -l [device]", description: "List ext filesystem information", category: "system"},
            {id: 61, name: "resize2fs [device]", description: "Ext2/3/4 file system resizer", category: "system"},
            {id: 62, name: "badblocks [device]", description: "Search a device for bad blocks", category: "system"},
            {id: 63, name: "dd if=/dev/zero of=[file] bs=1M count=100", description: "Create a 100MB test file", category: "system"},
            {id: 64, name: "dd if=/dev/urandom of=[file] bs=1M count=100", description: "Create a 100MB random file", category: "system"},
            {id: 65, name: "dd if=/dev/sda of=/dev/sdb bs=4M", description: "Clone one disk to another", category: "system"},
            {id: 66, name: "sync", description: "Flush filesystem buffers", category: "system"},
            {id: 67, name: "lsof", description: "List open files", category: "system"},
            {id: 68, name: "lsof -i", description: "List open network files", category: "system"},
            {id: 69, name: "fuser [file]", description: "Identify processes using files or sockets", category: "system"},
            {id: 70, name: "strace [command]", description: "Trace system calls and signals", category: "system"},
            {id: 71, name: "ltrace [command]", description: "Trace library calls", category: "system"},
            {id: 72, name: "time [command]", description: "Time a simple command", category: "system"},
            {id: 73, name: "timeout [time] [command]", description: "Run command with time limit", category: "system"},
            {id: 74, name: "watch [command]", description: "Execute program periodically", category: "system"},
            {id: 75, name: "nohup [command]", description: "Run command immune to hangups", category: "system"},
            {id: 76, name: "setsid [command]", description: "Run program in a new session", category: "system"},
            {id: 77, name: "chroot [directory] [command]", description: "Run command with special root directory", category: "system"},
            {id: 78, name: "systemctl", description: "Control the systemd system and service manager", category: "system"},
            {id: 79, name: "service [service] [action]", description: "Run a System V init script", category: "system"},
            {id: 80, name: "init [runlevel]", description: "Change system runlevel", category: "system"},
            {id: 81, name: "runlevel", description: "Print previous and current runlevel", category: "system"},
            {id: 82, name: "telinit [runlevel]", description: "Change runlevel", category: "system"},
            {id: 83, name: "shutdown -h now", description: "Shutdown the system", category: "system"},
            {id: 84, name: "shutdown -r now", description: "Reboot the system", category: "system"},
            {id: 85, name: "reboot", description: "Reboot the system", category: "system"},
            {id: 86, name: "halt", description: "Halt the system", category: "system"},
            {id: 87, name: "poweroff", description: "Power-off the system", category: "system"},
            {id: 88, name: "wall [message]", description: "Send message to all users", category: "system"},
            {id: 89, name: "mesg [y|n]", description: "Control write access to your terminal", category: "system"},
            {id: 90, name: "write [user] [tty]", description: "Send message to another user", category: "system"},
            {id: 91, name: "talk [user]", description: "Talk to another user", category: "system"},
            {id: 92, name: "finger [user]", description: "User information lookup program", category: "system"},
            {id: 93, name: "chage -l [user]", description: "Display password aging information", category: "system"},
            {id: 94, name: "passwd [user]", description: "Change user password", category: "system"},
            {id: 95, name: "pwck", description: "Verify integrity of password files", category: "system"},
            {id: 96, name: "grpck", description: "Verify integrity of group files", category: "system"},
            {id: 97, name: "vipw", description: "Edit the password file", category: "system"},
            {id: 98, name: "vigr", description: "Edit the group file", category: "system"},
            {id: 99, name: "getent passwd", description: "Get password file entries", category: "system"},
            {id: 100, name: "getent group", description: "Get group file entries", category: "system"},

            // Package management commands (100)
            {id: 101, name: "pkg update", description: "Update package lists", category: "package"},
            {id: 102, name: "pkg upgrade", description: "Upgrade all installed packages", category: "package"},
            {id: 103, name: "pkg install [package]", description: "Install a package", category: "package"},
            {id: 104, name: "pkg remove [package]", description: "Remove a package", category: "package"},
            {id: 105, name: "pkg autoremove", description: "Remove unneeded packages", category: "package"},
            {id: 106, name: "pkg list-installed", description: "List installed packages", category: "package"},
            {id: 107, name: "pkg search [query]", description: "Search for packages", category: "package"},
            {id: 108, name: "pkg show [package]", description: "Show package information", category: "package"},
            {id: 109, name: "pkg files [package]", description: "List files installed by package", category: "package"},
            {id: 110, name: "pkg list-all", description: "List all available packages", category: "package"},
            {id: 111, name: "pkg clean", description: "Clean package cache", category: "package"},
            {id: 112, name: "pkg autoclean", description: "Remove obsolete package files", category: "package"},
            {id: 113, name: "pkg reinstall [package]", description: "Reinstall a package", category: "package"},
            {id: 114, name: "pkg hold [package]", description: "Hold package from being upgraded", category: "package"},
            {id: 115, name: "pkg unhold [package]", description: "Remove hold on package", category: "package"},
            {id: 116, name: "pkg history", description: "View package management history", category: "package"},
            {id: 117, name: "pkg policy [package]", description: "Show package installation policy", category: "package"},
            {id: 118, name: "pkg purge [package]", description: "Remove package and configuration files", category: "package"},
            {id: 119, name: "pkg depends [package]", description: "Show package dependencies", category: "package"},
            {id: 120, name: "pkg rdepends [package]", description: "Show reverse dependencies", category: "package"},
            {id: 121, name: "pkg download [package]", description: "Download package without installing", category: "package"},
            {id: 122, name: "pkg source [package]", description: "Download source package", category: "package"},
            {id: 123, name: "pkg build-dep [package]", description: "Install build dependencies", category: "package"},
            {id: 124, name: "pkg satisfy [dep]", description: "Install packages to satisfy dependency", category: "package"},
            {id: 125, name: "pkg add-architecture [arch]", description: "Add architecture for multi-arch support", category: "package"},
            {id: 126, name: "pkg remove-architecture [arch]", description: "Remove architecture", category: "package"},
            {id: 127, name: "pkg print-architecture", description: "Display architectures configured", category: "package"},
            {id: 128, name: "pkg configure -a", description: "Configure all unpacked but unconfigured packages", category: "package"},
            {id: 129, name: "pkg --get-selections", description: "List package selections", category: "package"},
            {id: 130, name: "pkg --set-selections", description: "Set package selections from stdin", category: "package"},
            {id: 131, name: "pkg --clear-selections", description: "Deselect every non-essential package", category: "package"},
            {id: 132, name: "pkg --purge --get-selections", description: "List packages selected for removal", category: "package"},
            {id: 133, name: "pkg --compare-versions [ver1] [op] [ver2]", description: "Compare version numbers", category: "package"},
            {id: 134, name: "pkg --force [action]", description: "Force an operation", category: "package"},
            {id: 135, name: "pkg --no-act [command]", description: "Dry run - don't actually change system", category: "package"},
            {id: 136, name: "pkg --simulate [command]", description: "Simulate command execution", category: "package"},
            {id: 137, name: "pkg --ignore-depends=[package]", description: "Ignore dependencies on package", category: "package"},
            {id: 138, name: "pkg --skip-same-version", description: "Skip packages whose versions are already installed", category: "package"},
            {id: 139, name: "pkg --skip-broken", description: "Skip packages with broken dependencies", category: "package"},
            {id: 140, name: "pkg --fix-broken", description: "Fix broken dependencies", category: "package"},
            {id: 141, name: "pkg --triggers-only [package]", description: "Process only triggers", category: "package"},
            {id: 142, name: "pkg --no-triggers", description: "Skip processing triggers", category: "package"},
            {id: 143, name: "pkg --verify [package]", description: "Verify package integrity", category: "package"},
            {id: 144, name: "pkg --audit", description: "Audit installed packages", category: "package"},
            {id: 145, name: "pkg --get-suggestions", description: "Get suggested packages", category: "package"},
            {id: 146, name: "pkg --install-suggests", description: "Install suggested packages", category: "package"},
            {id: 147, name: "pkg --install-recommends", description: "Install recommended packages", category: "package"},
            {id: 148, name: "pkg --no-install-recommends", description: "Don't install recommended packages", category: "package"},
            {id: 149, name: "pkg --install-optional", description: "Install optional packages", category: "package"},
            {id: 150, name: "pkg --no-install-optional", description: "Don't install optional packages", category: "package"},
            {id: 151, name: "pkg --with-source [file]", description: "Use package file as source", category: "package"},
            {id: 152, name: "pkg --without-source [file]", description: "Don't use package file as source", category: "package"},
            {id: 153, name: "pkg --diff [file1] [file2]", description: "Compare package files", category: "package"},
            {id: 154, name: "pkg --merge [file1] [file2]", description: "Merge package files", category: "package"},
            {id: 155, name: "pkg --extract [file] [dir]", description: "Extract package contents", category: "package"},
            {id: 156, name: "pkg --contents [file]", description: "List package contents", category: "package"},
            {id: 157, name: "pkg --info [file]", description: "Show package information", category: "package"},
            {id: 158, name: "pkg --field [file] [field]", description: "Show package field", category: "package"},
            {id: 159, name: "pkg --status", description: "Display package status", category: "package"},
            {id: 160, name: "pkg --print-avail [package]", description: "Display available version details", category: "package"},
            {id: 161, name: "pkg --print-architecture", description: "Display architecture", category: "package"},
            {id: 162, name: "pkg --compare-versions", description: "Compare version numbers", category: "package"},
            {id: 163, name: "pkg --assert-multi-arch", description: "Assert multi-arch support", category: "package"},
            {id: 164, name: "pkg --assert-support-predepends", description: "Assert pre-depends support", category: "package"},
            {id: 165, name: "pkg --assert-working-epoch", description: "Assert epoch support", category: "package"},
            {id: 166, name: "pkg --assert-long-filenames", description: "Assert long filename support", category: "package"},
            {id: 167, name: "pkg --assert-feature [feature]", description: "Assert feature support", category: "package"},
            {id: 168, name: "pkg --assert-version-support [version]", description: "Assert version support", category: "package"},
            {id: 169, name: "pkg --assert-multi-conrep", description: "Assert multi-conrep support", category: "package"},
            {id: 170, name: "pkg --assert-multi-version", description: "Assert multi-version support", category: "package"},
            {id: 171, name: "pkg --assert-hold", description: "Assert hold support", category: "package"},
            {id: 172, name: "pkg --assert-not-installed [package]", description: "Assert package not installed", category: "package"},
            {id: 173, name: "pkg --assert-installed [package]", description: "Assert package installed", category: "package"},
            {id: 174, name: "pkg --assert-version [package] [version]", description: "Assert package version", category: "package"},
            {id: 174, name: "pkg --assert-version [package] [version]", description: "Assert package version", category: "package"},
            {id: 175, name: "pkg --assert-status [package] [status]", description: "Assert package status", category: "package"},
            {id: 176, name: "pkg --assert-recommends [package]", description: "Assert package recommends", category: "package"},
            {id: 177, name: "pkg --assert-suggests [package]", description: "Assert package suggests", category: "package"},
            {id: 178, name: "pkg --assert-depends [package] [dep]", description: "Assert package dependency", category: "package"},
            {id: 179, name: "pkg --assert-predepends [package] [dep]", description: "Assert package pre-dependency", category: "package"},
            {id: 180, name: "pkg --assert-breaks [package] [dep]", description: "Assert package break", category: "package"},
            {id: 181, name: "pkg --assert-conflicts [package] [dep]", description: "Assert package conflict", category: "package"},
            {id: 182, name: "pkg --assert-provides [package] [dep]", description: "Assert package provides", category: "package"},
            {id: 183, name: "pkg --assert-replaces [package] [dep]", description: "Assert package replaces", category: "package"},
            {id: 184, name: "pkg --assert-enhances [package] [dep]", description: "Assert package enhances", category: "package"},
            {id: 185, name: "pkg --assert-obsoletes [package] [dep]", description: "Assert package obsoletes", category: "package"},
            {id: 186, name: "pkg --assert-source [package]", description: "Assert source package", category: "package"},
            {id: 187, name: "pkg --assert-binary [package]", description: "Assert binary package", category: "package"},
            {id: 188, name: "pkg --assert-arch [package] [arch]", description: "Assert package architecture", category: "package"},
            {id: 189, name: "pkg --assert-not-arch [package] [arch]", description: "Assert package not architecture", category: "package"},
            {id: 190, name: "pkg --assert-multi-arch [package]", description: "Assert package multi-arch", category: "package"},
            {id: 191, name: "pkg --assert-not-multi-arch [package]", description: "Assert package not multi-arch", category: "package"},
            {id: 192, name: "pkg --assert-essential [package]", description: "Assert package essential", category: "package"},
            {id: 193, name: "pkg --assert-not-essential [package]", description: "Assert package not essential", category: "package"},
            {id: 194, name: "pkg --assert-important [package]", description: "Assert package important", category: "package"},
            {id: 195, name: "pkg --assert-not-important [package]", description: "Assert package not important", category: "package"},
            {id: 196, name: "pkg --assert-standard [package]", description: "Assert package standard", category: "package"},
            {id: 197, name: "pkg --assert-not-standard [package]", description: "Assert package not standard", category: "package"},
            {id: 198, name: "pkg --assert-virtual [package]", description: "Assert package virtual", category: "package"},
            {id: 199, name: "pkg --assert-not-virtual [package]", description: "Assert package not virtual", category: "package"},
            {id: 200, name: "pkg --assert-meta [package]", description: "Assert package meta", category: "package"},

            // File management commands (100)
            {id: 201, name: "ls", description: "List directory contents", category: "file"},
            {id: 202, name: "ls -l", description: "List with long format", category: "file"},
            {id: 203, name: "ls -a", description: "List including hidden files", category: "file"},
            {id: 204, name: "ls -lh", description: "List with human-readable sizes", category: "file"},
            {id: 205, name: "ls -t", description: "List sorted by modification time", category: "file"},
            {id: 206, name: "ls -S", description: "List sorted by file size", category: "file"},
            {id: 207, name: "ls -R", description: "List recursively", category: "file"},
            {id: 208, name: "ls -d */", description: "List only directories", category: "file"},
            {id: 209, name: "tree", description: "Display directory tree", category: "file"},
            {id: 210, name: "cd [dir]", description: "Change directory", category: "file"},
            {id: 211, name: "cd ~", description: "Change to home directory", category: "file"},
            {id: 212, name: "cd -", description: "Change to previous directory", category: "file"},
            {id: 213, name: "cd ..", description: "Change to parent directory", category: "file"},
            {id: 214, name: "pwd", description: "Print working directory", category: "file"},
            {id: 215, name: "mkdir [dir]", description: "Create directory", category: "file"},
            {id: 216, name: "mkdir -p [path]", description: "Create directory path", category: "file"},
            {id: 217, name: "rmdir [dir]", description: "Remove empty directory", category: "file"},
            {id: 218, name: "rm -r [dir]", description: "Remove directory recursively", category: "file"},
            {id: 219, name: "rm -rf [dir]", description: "Force remove directory recursively", category: "file"},
            {id: 220, name: "touch [file]", description: "Create empty file or update timestamp", category: "file"},
            {id: 221, name: "cp [src] [dest]", description: "Copy file", category: "file"},
            {id: 222, name: "cp -r [src] [dest]", description: "Copy directory recursively", category: "file"},
            {id: 223, name: "cp -v [src] [dest]", description: "Copy verbosely", category: "file"},
            {id: 224, name: "cp -i [src] [dest]", description: "Copy with confirmation", category: "file"},
            {id: 225, name: "mv [src] [dest]", description: "Move or rename file/directory", category: "file"},
            {id: 226, name: "mv -i [src] [dest]", description: "Move with confirmation", category: "file"},
            {id: 227, name: "rm [file]", description: "Remove file", category: "file"},
            {id: 228, name: "rm -i [file]", description: "Remove with confirmation", category: "file"},
            {id: 229, name: "rm -f [file]", description: "Force remove without confirmation", category: "file"},
            {id: 230, name: "ln -s [target] [link]", description: "Create symbolic link", category: "file"},
            {id: 231, name: "ln [target] [link]", description: "Create hard link", category: "file"},
            {id: 232, name: "cat [file]", description: "Display file contents", category: "file"},
            {id: 233, name: "tac [file]", description: "Display file contents in reverse", category: "file"},
            {id: 234, name: "less [file]", description: "View file interactively", category: "file"},
            {id: 235, name: "more [file]", description: "View file page by page", category: "file"},
            {id: 236, name: "head [file]", description: "Display first lines of file", category: "file"},
            {id: 237, name: "head -n 10 [file]", description: "Display first 10 lines", category: "file"},
            {id: 238, name: "tail [file]", description: "Display last lines of file", category: "file"},
            {id: 239, name: "tail -n 10 [file]", description: "Display last 10 lines", category: "file"},
            {id: 240, name: "tail -f [file]", description: "Follow file as it grows", category: "file"},
            {id: 241, name: "grep [pattern] [file]", description: "Search for pattern in file", category: "file"},
            {id: 242, name: "grep -r [pattern] [dir]", description: "Search recursively in directory", category: "file"},
            {id: 243, name: "grep -i [pattern] [file]", description: "Case-insensitive search", category: "file"},
            {id: 244, name: "grep -v [pattern] [file]", description: "Invert match", category: "file"},
            {id: 245, name: "grep -l [pattern] [dir]", description: "Show only matching filenames", category: "file"},
            {id: 246, name: "grep -c [pattern] [file]", description: "Count matches", category: "file"},
            {id: 247, name: "grep -n [pattern] [file]", description: "Show line numbers", category: "file"},
            {id: 248, name: "grep -E [pattern] [file]", description: "Extended regex", category: "file"},
            {id: 249, name: "find [dir] -name [pattern]", description: "Find files by name", category: "file"},
            {id: 250, name: "find [dir] -type f", description: "Find only files", category: "file"},
            {id: 251, name: "find [dir] -type d", description: "Find only directories", category: "file"},
            {id: 252, name: "find [dir] -mtime -7", description: "Find modified in last 7 days", category: "file"},
            {id: 253, name: "find [dir] -size +1M", description: "Find files larger than 1MB", category: "file"},
            {id: 254, name: "find [dir] -empty", description: "Find empty files/directories", category: "file"},
            {id: 255, name: "find [dir] -perm 644", description: "Find files with specific permissions", category: "file"},
            {id: 256, name: "find [dir] -user [user]", description: "Find files owned by user", category: "file"},
            {id: 257, name: "find [dir] -group [group]", description: "Find files owned by group", category: "file"},
            {id: 258, name: "find [dir] -exec [command] {} \\;", description: "Execute command on found files", category: "file"},
            {id: 259, name: "locate [pattern]", description: "Find files quickly using database", category: "file"},
            {id: 260, name: "updatedb", description: "Update locate database", category: "file"},
            {id: 261, name: "which [command]", description: "Show full path of command", category: "file"},
            {id: 262, name: "whereis [command]", description: "Locate binary, source, and manual", category: "file"},
            {id: 263, name: "type [command]", description: "Display command type", category: "file"},
            {id: 264, name: "file [file]", description: "Determine file type", category: "file"},
            {id: 265, name: "stat [file]", description: "Display file status", category: "file"},
            {id: 266, name: "du -sh [dir]", description: "Show directory size", category: "file"},
            {id: 267, name: "du -h [dir]", description: "Show sizes of contents", category: "file"},
            {id: 268, name: "df -h", description: "Show disk usage", category: "file"},
            {id: 269, name: "df -i", description: "Show inode usage", category: "file"},
            {id: 270, name: "mount", description: "Show mounted filesystems", category: "file"},
            {id: 271, name: "umount [device]", description: "Unmount filesystem", category: "file"},
            {id: 272, name: "fsck [device]", description: "Check and repair filesystem", category: "file"},
            {id: 273, name: "mkfs.ext4 [device]", description: "Create ext4 filesystem", category: "file"},
            {id: 274, name: "dd if=[input] of=[output]", description: "Convert and copy files", category: "file"},
            {id: 275, name: "dd if=/dev/zero of=[file] bs=1M count=100", description: "Create 100MB test file", category: "file"},
            {id: 276, name: "dd if=/dev/urandom of=[file] bs=1M count=100", description: "Create 100MB random file", category: "file"},
            {id: 277, name: "rsync -av [src] [dest]", description: "Synchronize files/directories", category: "file"},
            {id: 278, name: "rsync -avz [src] [dest]", description: "Synchronize with compression", category: "file"},
            {id: 279, name: "rsync -av --delete [src] [dest]", description: "Synchronize with deletion", category: "file"},
            {id: 280, name: "scp [file] [user]@[host]:[path]", description: "Securely copy file to remote host", category: "file"},
            {id: 281, name: "scp [user]@[host]:[file] [dest]", description: "Securely copy file from remote host", category: "file"},
            {id: 282, name: "scp -r [dir] [user]@[host]:[path]", description: "Securely copy directory recursively", category: "file"},
            {id: 283, name: "tar -cvf [archive.tar] [files]", description: "Create tar archive", category: "file"},
            {id: 284, name: "tar -xvf [archive.tar]", description: "Extract tar archive", category: "file"},
            {id: 285, name: "tar -czvf [archive.tar.gz] [files]", description: "Create compressed tar archive", category: "file"},
            {id: 286, name: "tar -xzvf [archive.tar.gz]", description: "Extract compressed tar archive", category: "file"},
            {id: 287, name: "gzip [file]", description: "Compress file with gzip", category: "file"},
            {id: 288, name: "gunzip [file.gz]", description: "Decompress gzip file", category: "file"},
            {id: 289, name: "zip [archive.zip] [files]", description: "Create zip archive", category: "file"},
            {id: 290, name: "unzip [archive.zip]", description: "Extract zip archive", category: "file"},
            {id: 291, name: "bzip2 [file]", description: "Compress file with bzip2", category: "file"},
            {id: 292, name: "bunzip2 [file.bz2]", description: "Decompress bzip2 file", category: "file"},
            {id: 293, name: "xz [file]", description: "Compress file with xz", category: "file"},
            {id: 294, name: "unxz [file.xz]", description: "Decompress xz file", category: "file"},
            {id: 295, name: "7z a [archive.7z] [files]", description: "Create 7z archive", category: "file"},
            {id: 296, name: "7z x [archive.7z]", description: "Extract 7z archive", category: "file"},
            {id: 297, name: "rar a [archive.rar] [files]", description: "Create rar archive", category: "file"},
            {id: 298, name: "rar x [archive.rar]", description: "Extract rar archive", category: "file"},
            {id: 299, name: "chmod [mode] [file]", description: "Change file permissions", category: "file"},
            {id: 300, name: "chmod 755 [file]", description: "Set rwxr-xr-x permissions", category: "file"},

            // Networking commands (100)
            {id: 301, name: "ping [host]", description: "Test network connectivity", category: "network"},
            {id: 302, name: "ping -c 4 [host]", description: "Send 4 ping packets", category: "network"},
            {id: 303, name: "traceroute [host]", description: "Trace route to host", category: "network"},
            {id: 304, name: "mtr [host]", description: "Combination of ping and traceroute", category: "network"},
            {id: 305, name: "ifconfig", description: "Configure network interfaces", category: "network"},
            {id: 306, name: "ifconfig [interface] up", description: "Bring interface up", category: "network"},
            {id: 307, name: "ifconfig [interface] down", description: "Bring interface down", category: "network"},
            {id: 308, name: "ip addr", description: "Show IP addresses", category: "network"},
            {id: 309, name: "ip link", description: "Show network interfaces", category: "network"},
            {id: 310, name: "ip route", description: "Show routing table", category: "network"},
            {id: 311, name: "route -n", description: "Show routing table", category: "network"},
            {id: 312, name: "netstat -tuln", description: "Show listening ports", category: "network"},
            {id: 313, name: "netstat -tulnp", description: "Show listening ports with PIDs", category: "network"},
            {id: 314, name: "netstat -r", description: "Show routing table", category: "network"},
            {id: 315, name: "netstat -s", description: "Show network statistics", category: "network"},
            {id: 316, name: "ss -tuln", description: "Show listening ports (modern)", category: "network"},
            {id: 317, name: "ss -s", description: "Show socket statistics", category: "network"},
            {id: 318, name: "dig [domain]", description: "DNS lookup utility", category: "network"},
            {id: 319, name: "dig +short [domain]", description: "Short DNS lookup", category: "network"},
            {id: 320, name: "dig -x [ip]", description: "Reverse DNS lookup", category: "network"},
            {id: 321, name: "nslookup [domain]", description: "Query Internet name servers", category: "network"},
            {id: 322, name: "host [domain]", description: "DNS lookup utility", category: "network"},
            {id: 323, name: "whois [domain]", description: "Domain information lookup", category: "network"},
            {id: 324, name: "curl [url]", description: "Transfer data from URL", category: "network"},
            {id: 325, name: "curl -O [url]", description: "Download file", category: "network"},
            {id: 326, name: "curl -L [url]", description: "Follow redirects", category: "network"},
            {id: 327, name: "curl -I [url]", description: "Show headers only", category: "network"},
            {id: 328, name: "curl -v [url]", description: "Verbose output", category: "network"},
            {id: 329, name: "wget [url]", description: "Download file from web", category: "network"},
            {id: 330, name: "wget -c [url]", description: "Continue interrupted download", category: "network"},
            {id: 331, name: "wget -r [url]", description: "Download recursively", category: "network"},
            {id: 332, name: "wget -mk [url]", description: "Mirror website", category: "network"},
            {id: 333, name: "ssh [user]@[host]", description: "Secure shell client", category: "network"},
            {id: 334, name: "ssh -p [port] [user]@[host]", description: "SSH with custom port", category: "network"},
            {id: 335, name: "ssh -i [key] [user]@[host]", description: "SSH with identity file", category: "network"},
            {id: 336, name: "ssh -v [user]@[host]", description: "Verbose SSH", category: "network"},
            {id: 337, name: "ssh -L [port]:[host]:[port] [user]@[gateway]", description: "Local port forwarding", category: "network"},
            {id: 338, name: "ssh -R [port]:[host]:[port] [user]@[gateway]", description: "Remote port forwarding", category: "network"},
            {id: 339, name: "ssh -D [port] [user]@[host]", description: "Dynamic port forwarding (SOCKS)", category: "network"},
            {id: 340, name: "scp [file] [user]@[host]:[path]", description: "Secure copy to remote host", category: "network"},
            {id: 341, name: "scp [user]@[host]:[file] [dest]", description: "Secure copy from remote host", category: "network"},
            {id: 342, name: "scp -P [port] [file] [user]@[host]:[path]", description: "SCP with custom port", category: "network"},
            {id: 343, name: "scp -r [dir] [user]@[host]:[path]", description: "Recursive SCP", category: "network"},
            {id: 344, name: "sftp [user]@[host]", description: "Secure file transfer program", category: "network"},
            {id: 345, name: "rsync -avz [src] [user]@[host]:[dest]", description: "Sync files to remote host", category: "network"},
            {id: 346, name: "rsync -avz [user]@[host]:[src] [dest]", description: "Sync files from remote host", category: "network"},
            {id: 347, name: "rsync -avz -e ssh [src] [dest]", description: "RSYNC over SSH", category: "network"},
            {id: 348, name: "nc [host] [port]", description: "Netcat - read/write network connections", category: "network"},
            {id: 349, name: "nc -l [port]", description: "Netcat listen on port", category: "network"},
            {id: 350, name: "nc -vz [host] [port]", description: "Test if port is open", category: "network"},
            {id: 351, name: "nc -w [timeout] [host] [port]", description: "Netcat with timeout", category: "network"},
            {id: 352, name: "ncat [host] [port]", description: "Improved netcat", category: "network"},
            {id: 353, name: "ncat -l [port]", description: "Ncat listen on port", category: "network"},
            {id: 354, name: "ncat -vz [host] [port]", description: "Test if port is open with Ncat", category: "network"},
            {id: 355, name: "ncat -w [timeout] [host] [port]", description: "Ncat with timeout", category: "network"},
            {id: 356, name: "telnet [host] [port]", description: "Telnet client", category: "network"},
            {id: 357, name: "ftp [host]", description: "FTP client", category: "network"},
            {id: 358, name: "socat [options]", description: "Multipurpose relay", category: "network"},
            {id: 359, name: "socat TCP-LISTEN:[port] STDOUT", description: "Listen and print incoming data", category: "network"},
            {id: 360, name: "socat TCP:[host]:[port] STDIN", description: "Connect and send stdin", category: "network"},
            {id: 361, name: "socat UDP-LISTEN:[port] STDOUT", description: "UDP listen and print", category: "network"},
            {id: 362, name: "socat UDP:[host]:[port] STDIN", description: "UDP connect and send", category: "network"},
            {id: 363, name: "socat OPENSSL-LISTEN:[port],cert=[cert.pem] STDOUT", description: "SSL listen", category: "network"},
            {id: 364, name: "socat OPENSSL:[host]:[port],verify=0 STDIN", description: "SSL connect", category: "network"},
            {id: 365, name: "socat EXEC:'bash -li',pty,stderr,setsid,sigint,sane TCP:[host]:[port]", description: "Reverse shell", category: "network"},
            {id: 366, name: "nmap [host]", description: "Network exploration tool", category: "network"},
            {id: 367, name: "nmap -sS [host]", description: "TCP SYN scan", category: "network"},
            {id: 368, name: "nmap -sT [host]", description: "TCP connect scan", category: "network"},
            {id: 369, name: "nmap -sU [host]", description: "UDP scan", category: "network"},
            {id: 370, name: "nmap -sV [host]", description: "Version detection", category: "network"},
            {id: 371, name: "nmap -O [host]", description: "OS detection", category: "network"},
            {id: 372, name: "nmap -A [host]", description: "Aggressive scan", category: "network"},
            {id: 373, name: "nmap -p [port] [host]", description: "Scan specific port", category: "network"},
            {id: 374, name: "nmap -p- [host]", description: "Scan all ports", category: "network"},
            {id: 375, name: "nmap -iL [file]", description: "Scan targets from file", category: "network"},
            {id: 376, name: "nmap --script [script] [host]", description: "Run NSE script", category: "network"},
            {id: 377, name: "nmap --script-help [script]", description: "Show NSE script help", category: "network"},
            {id: 378, name: "nmap --script-updatedb", description: "Update NSE script database", category: "network"},
            {id: 379, name: "nmap -oN [file] [host]", description: "Save output to file", category: "network"},
            {id: 380, name: "nmap -oX [file] [host]", description: "Save output as XML", category: "network"},
            {id: 381, name: "nmap -oG [file] [host]", description: "Save output in grepable format", category: "network"},
            {id: 382, name: "nmap -v [host]", description: "Verbose output", category: "network"},
            {id: 383, name: "nmap -d [host]", description: "Debug output", category: "network"},
            {id: 384, name: "nmap -T4 [host]", description: "Aggressive timing template", category: "network"},
            {id: 385, name: "nmap -6 [host]", description: "IPv6 scan", category: "network"},
            {id: 386, name: "nmap --top-ports [num] [host]", description: "Scan top ports", category: "network"},
            {id: 387, name: "nmap --min-rate [num] [host]", description: "Send packets no slower than rate", category: "network"},
            {id: 388, name: "nmap --max-rate [num] [host]", description: "Send packets no faster than rate", category: "network"},
            {id: 389, name: "nmap --min-parallelism [num] [host]", description: "Minimum parallel probes", category: "network"},
            {id: 390, name: "nmap --max-parallelism [num] [host]", description: "Maximum parallel probes", category: "network"},
            {id: 391, name: "nmap --min-hostgroup [num] [host]", description: "Minimum host group size", category: "network"},
            {id: 392, name: "nmap --max-hostgroup [num] [host]", description: "Maximum host group size", category: "network"},
            {id: 393, name: "nmap --min-rtt-timeout [time] [host]", description: "Minimum RTT timeout", category: "network"},
            {id: 394, name: "nmap --max-rtt-timeout [time] [host]", description: "Maximum RTT timeout", category: "network"},
            {id: 395, name: "nmap --initial-rtt-timeout [time] [host]", description: "Initial RTT timeout", category: "network"},
            {id: 396, name: "nmap --host-timeout [time] [host]", description: "Host timeout", category: "network"},
            {id: 397, name: "nmap --scan-delay [time] [host]", description: "Delay between probes", category: "network"},
            {id: 398, name: "nmap --max-scan-delay [time] [host]", description: "Maximum delay between probes", category: "network"},
            {id: 399, name: "nmap --min-rate [num] [host]", description: "Send packets no slower than rate", category: "network"},
            {id: 400, name: "nmap --max-retries [num] [host]", description: "Maximum retries", category: "network"},

            // Development commands (100)
            {id: 401, name: "git init", description: "Initialize git repository", category: "dev"},
            {id: 402, name: "git clone [repo]", description: "Clone repository", category: "dev"},
            {id: 403, name: "git add [file]", description: "Add file to staging area", category: "dev"},
            {id: 404, name: "git add .", description: "Add all files to staging area", category: "dev"},
            {id: 405, name: "git commit -m '[message]'", description: "Commit changes with message", category: "dev"},
            {id: 406, name: "git status", description: "Show working tree status", category: "dev"},
            {id: 407, name: "git log", description: "Show commit logs", category: "dev"},
            {id: 408, name: "git log --oneline", description: "Show compact commit logs", category: "dev"},
            {id: 409, name: "git log --graph", description: "Show commit graph", category: "dev"},
            {id: 410, name: "git diff", description: "Show changes not staged", category: "dev"},
            {id: 411, name: "git diff --cached", description: "Show staged changes", category: "dev"},
            {id: 412, name: "git branch", description: "List branches", category: "dev"},
            {id: 413, name: "git branch [name]", description: "Create branch", category: "dev"},
            {id: 414, name: "git checkout [branch]", description: "Switch to branch", category: "dev"},
            {id: 415, name: "git checkout -b [branch]", description: "Create and switch to branch", category: "dev"},
            {id: 416, name: "git merge [branch]", description: "Merge branch into current", category: "dev"},
            {id: 417, name: "git rebase [branch]", description: "Rebase current branch onto another", category: "dev"},
            {id: 418, name: "git reset [file]", description: "Unstage file", category: "dev"},
            {id: 419, name: "git reset --hard", description: "Reset all changes", category: "dev"},
            {id: 420, name: "git revert [commit]", description: "Revert commit", category: "dev"},
            {id: 421, name: "git stash", description: "Stash changes", category: "dev"},
            {id: 422, name: "git stash pop", description: "Apply stashed changes", category: "dev"},
            {id: 423, name: "git remote add [name] [url]", description: "Add remote repository", category: "dev"},
            {id: 424, name: "git remote -v", description: "List remote repositories", category: "dev"},
            {id: 425, name: "git fetch [remote]", description: "Download objects from remote", category: "dev"},
            {id: 426, name: "git pull [remote] [branch]", description: "Fetch and merge from remote", category: "dev"},
            {id: 427, name: "git push [remote] [branch]", description: "Push to remote repository", category: "dev"},
            {id: 428, name: "git push -u [remote] [branch]", description: "Push and set upstream", category: "dev"},
            {id: 429, name: "git tag [name]", description: "Create tag", category: "dev"},
            {id: 430, name: "git tag -a [name] -m '[message]'", description: "Create annotated tag", category: "dev"},
            {id: 431, name: "git show [commit]", description: "Show commit details", category: "dev"},
            {id: 432, name: "git blame [file]", description: "Show who changed each line", category: "dev"},
            {id: 433, name: "git grep [pattern]", description: "Search working tree", category: "dev"},
            {id: 434, name: "git config --global user.name '[name]'", description: "Set global username", category: "dev"},
            {id: 435, name: "git config --global user.email '[email]'", description: "Set global email", category: "dev"},
            {id: 436, name: "git config --list", description: "List configuration", category: "dev"},
            {id: 437, name: "git help [command]", description: "Show help for command", category: "dev"},
            {id: 438, name: "python [script.py]", description: "Run Python script", category: "dev"},
            {id: 439, name: "python -m [module]", description: "Run Python module", category: "dev"},
            {id: 440, name: "python -c '[code]'", description: "Execute Python code", category: "dev"},
            {id: 441, name: "python -i [script.py]", description: "Run script then enter interactive mode", category: "dev"},
            {id: 442, name: "python -m pdb [script.py]", description: "Run with debugger", category: "dev"},
            {id: 443, name: "python -m venv [dir]", description: "Create virtual environment", category: "dev"},
            {id: 444, name: "source [dir]/bin/activate", description: "Activate virtual environment", category: "dev"},
            {id: 445, name: "deactivate", description: "Deactivate virtual environment", category: "dev"},
            {id: 446, name: "pip install [package]", description: "Install Python package", category: "dev"},
            {id: 447, name: "pip install -r requirements.txt", description: "Install from requirements file", category: "dev"},
            {id: 448, name: "pip install --upgrade [package]", description: "Upgrade package", category: "dev"},
            {id: 449, name: "pip uninstall [package]", description: "Uninstall package", category: "dev"},
            {id: 450, name: "pip freeze", description: "List installed packages", category: "dev"},
            {id: 451, name: "pip list", description: "List installed packages", category: "dev"},
            {id: 452, name: "pip show [package]", description: "Show package info", category: "dev"},
            {id: 453, name: "pip search [package]", description: "Search PyPI for packages", category: "dev"},
            {id: 454, name: "pip download [package]", description: "Download package without installing", category: "dev"},
            {id: 455, name: "pip wheel [package]", description: "Build wheel from requirements", category: "dev"},
            {id: 456, name: "pip check", description: "Verify installed packages have compatible dependencies", category: "dev"},
            {id: 457, name: "pip config list", description: "List configuration values", category: "dev"},
            {id: 458, name: "pip cache dir", description: "Show cache directory", category: "dev"},
            {id: 459, name: "pip cache info", description: "Show cache information", category: "dev"},
            {id: 460, name: "pip cache purge", description: "Remove files from cache", category: "dev"},
            {id: 461, name: "pip hash [file]", description: "Compute hash of package archive", category: "dev"},
            {id: 462, name: "pip debug", description: "Show debug information", category: "dev"},
            {id: 463, name: "pip --version", description: "Show pip version", category: "dev"},
            {id: 464, name: "pip --help", description: "Show help", category: "dev"},
            {id: 465, name: "node [file.js]", description: "Run Node.js script", category: "dev"},
            {id: 466, name: "node -e '[code]'", description: "Execute Node.js code", category: "dev"},
            {id: 467, name: "node -v", description: "Show Node.js version", category: "dev"},
            {id: 468, name: "node -p 'process.arch'", description: "Show Node.js architecture", category: "dev"},
            {id: 469, name: "node -p 'process.platform'", description: "Show Node.js platform", category: "dev"},
            {id: 470, name: "node -p 'process.versions'", description: "Show Node.js versions", category: "dev"},
            {id: 471, name: "node -p 'process.env'", description: "Show Node.js environment", category: "dev"},
            {id: 472, name: "node -p 'process.cwd()'", description: "Show Node.js current working directory", category: "dev"},
            {id: 473, name: "node -p 'require.repl'", description: "Enter Node.js REPL", category: "dev"},
            {id: 474, name: "node --inspect [file.js]", description: "Enable inspector", category: "dev"},
            {id: 475, name: "node --inspect-brk [file.js]", description: "Enable inspector and break at start", category: "dev"},
            {id: 476, name: "node --prof [file.js]", description: "Generate V8 profiler output", category: "dev"},
            {id: 477, name: "node --trace-warnings [file.js]", description: "Print stack traces for warnings", category: "dev"},
            {id: 478, name: "node --trace-deprecation [file.js]", description: "Print stack traces for deprecations", category: "dev"},
            {id: 479, name: "node --throw-deprecation [file.js]", description: "Throw errors for deprecations", category: "dev"},
            {id: 480, name: "node --no-deprecation [file.js]", description: "Silence deprecation warnings", category: "dev"},
            {id: 481, name: "node --trace-sync-io [file.js]", description: "Print stack traces for sync IO", category: "dev"},
            {id: 482, name: "node --trace-events-enabled [file.js]", description: "Enable trace events", category: "dev"},
            {id: 483, name: "node --trace-event-categories [cats] [file.js]", description: "Set trace event categories", category: "dev"},
            {id: 484, name: "node --zero-fill-buffers [file.js]", description: "Automatically zero-fill buffers", category: "dev"},
            {id: 485, name: "node --track-heap-objects [file.js]", description: "Track heap object allocations", category: "dev"},
            {id: 486, name: "node --max-old-space-size=[size] [file.js]", description: "Set max old space size (MB)", category: "dev"},
            {id: 487, name: "node --max-semi-space-size=[size] [file.js]", description: "Set max semi space size (MB)", category: "dev"},
            {id: 488, name: "node --stack-size=[size] [file.js]", description: "Set stack size (KB)", category: "dev"},
            {id: 489, name: "node --v8-options", description: "Show V8 options", category: "dev"},
            {id: 490, name: "node --tls-cipher-list=[list] [file.js]", description: "Set TLS cipher list", category: "dev"},
            {id: 491, name: "node --icu-data-dir=[dir] [file.js]", description: "Set ICU data directory", category: "dev"},
            {id: 492, name: "node --openssl-config=[file] [file.js]", description: "Set OpenSSL config file", category: "dev"},
            {id: 493, name: "node --use-bundled-ca [file.js]", description: "Use bundled CA store", category: "dev"},
            {id: 494, name: "node --use-openssl-ca [file.js]", description: "Use OpenSSL CA store", category: "dev"},
            {id: 495, name: "node --enable-fips [file.js]", description: "Enable FIPS crypto", category: "dev"},
            {id: 496, name: "node --force-fips [file.js]", description: "Force FIPS crypto", category: "dev"},
            {id: 497, name: "node --pending-deprecation [file.js]", description: "Emit pending deprecation warnings", category: "dev"},
            {id: 498, name: "node --preserve-symlinks [file.js]", description: "Preserve symbolic links", category: "dev"},
            {id: 499, name: "node --preserve-symlinks-main [file.js]", description: "Preserve symbolic links for main module", category: "dev"},
            {id: 500, name: "node --prof-process [file]", description: "Process V8 profiler output", category: "dev"},

            // Security commands (100)
            {id: 501, name: "nmap -sV --script vuln [target]", description: "Scan for vulnerabilities", category: "security"},
            {id: 502, name: "nmap --script ssl-enum-ciphers -p 443 [target]", description: "Check SSL/TLS ciphers", category: "security"},
            {id: 503, name: "nikto -h [target]", description: "Web server scanner", category: "security"},
            {id: 504, name: "nikto -h [target] -p 80,443", description: "Scan specific ports", category: "security"},
            {id: 505, name: "nikto -h [target] -ssl", description: "Force SSL mode", category: "security"},
            {id: 506, name: "nikto -h [target] -Tuning 1", description: "Scan with tuning option 1 (interesting files)", category: "security"},
            {id: 507, name: "nikto -h [target] -Tuning 2", description: "Scan with tuning option 2 (misconfigurations)", category: "security"},
            {id: 508, name: "nikto -h [target] -Tuning 3", description: "Scan with tuning option 3 (information disclosure)", category: "security"},
            {id: 509, name: "nikto -h [target] -Tuning 4", description: "Scan with tuning option 4 (injection attacks)", category: "security"},
            {id: 510, name: "nikto -h [target] -Tuning 5", description: "Scan with tuning option 5 (remote file retrieval)", category: "security"},
            {id: 511, name: "nikto -h [target] -Tuning 6", description: "Scan with tuning option 6 (denial of service)", category: "security"},
            {id: 512, name: "nikto -h [target] -Tuning 7", description: "Scan with tuning option 7 (remote file inclusion)", category: "security"},
            {id: 513, name: "nikto -h [target] -Tuning 8", description: "Scan with tuning option 8 (command execution)", category: "security"},
            {id: 514, name: "nikto -h [target] -Tuning 9", description: "Scan with tuning option 9 (SQL injection)", category: "security"},
            {id: 515, name: "nikto -h [target] -Tuning 0", description: "Scan with tuning option 0 (file upload)", category: "security"},
            {id: 516, name: "nikto -h [target] -evasion 1", description: "Use evasion technique 1 (random URI encoding)", category: "security"},
            {id: 517, name: "nikto -h [target] -evasion 2", description: "Use evasion technique 2 (directory self-reference)", category: "security"},
            {id: 518, name: "nikto -h [target] -evasion 3", description: "Use evasion technique 3 (premature URL ending)", category: "security"},
            {id: 519, name: "nikto -h [target] -evasion 4", description: "Use evasion technique 4 (prepend long random string)", category: "security"},
            {id: 520, name: "nikto -h [target] -evasion 5", description: "Use evasion technique 5 (fake parameter)", category: "security"},
            {id: 521, name: "nikto -h [target] -evasion 6", description: "Use evasion technique 6 (TAB as request spacer)", category: "security"},
            {id: 522, name: "nikto -h [target] -evasion 7", description: "Use evasion technique 7 (change case)", category: "security"},
 {id: 523, name: "nikto -h [target] -evasion 8", description: "Use evasion technique 8 (use Windows path separator)", category: "security"},
            {id: 524, name: "sqlmap -u '[url]'", description: "SQL injection scanner", category: "security"},
            {id: 525, name: "sqlmap -u '[url]' --dbs", description: "Enumerate databases", category: "security"},
            {id: 526, name: "sqlmap -u '[url]' -D [db] --tables", description: "Enumerate tables in database", category: "security"},
            {id: 527, name: "sqlmap -u '[url]' -D [db] -T [table] --columns", description: "Enumerate columns in table", category: "security"},
            {id: 528, name: "sqlmap -u '[url]' -D [db] -T [table] -C [col] --dump", description: "Dump column data", category: "security"},
            {id: 529, name: "sqlmap -u '[url]' --os-shell", description: "Get an interactive OS shell", category: "security"},
            {id: 530, name: "sqlmap -u '[url]' --os-pwn", description: "Get an OOB shell, meterpreter or VNC", category: "security"},
            {id: 531, name: "sqlmap -u '[url]' --sql-shell", description: "Get an interactive SQL shell", category: "security"},
            {id: 532, name: "sqlmap -u '[url]' --file-read=[file]", description: "Read a file from the server", category: "security"},
            {id: 533, name: "sqlmap -u '[url]' --file-write=[src] --file-dest=[dest]", description: "Write a file on the server", category: "security"},
            {id: 534, name: "sqlmap -u '[url]' --wizard", description: "Simple wizard interface", category: "security"},
            {id: 535, name: "sqlmap -r [request.txt]", description: "Load HTTP request from file", category: "security"},
            {id: 536, name: "sqlmap -g '[google dork]'", description: "Process Google dork results", category: "security"},
            {id: 537, name: "sqlmap --crawl=[depth]", description: "Crawl website for URLs", category: "security"},
            {id: 538, name: "sqlmap --batch", description: "Never ask for user input", category: "security"},
            {id: 539, name: "sqlmap --level=[level]", description: "Level of tests to perform (1-5)", category: "security"},
            {id: 540, name: "sqlmap --risk=[risk]", description: "Risk of tests to perform (1-3)", category: "security"},
            {id: 541, name: "sqlmap --technique=[tech]", description: "SQL injection techniques to use", category: "security"},
            {id: 542, name: "sqlmap --tamper=[script]", description: "Use tamper script", category: "security"},
            {id: 543, name: "sqlmap --proxy=[proxy]", description: "Use a proxy", category: "security"},
            {id: 544, name: "sqlmap --tor", description: "Use Tor anonymity network", category: "security"},
            {id: 545, name: "sqlmap --check-tor", description: "Check if Tor is used properly", category: "security"},
            {id: 546, name: "sqlmap --random-agent", description: "Use randomly selected HTTP User-Agent", category: "security"},
            {id: 547, name: "sqlmap --auth-type=[type]", description: "HTTP authentication type", category: "security"},
            {id: 548, name: "sqlmap --auth-cred=[creds]", description: "HTTP authentication credentials", category: "security"},
            {id: 549, name: "sqlmap --cookie=[cookie]", description: "HTTP Cookie header value", category: "security"},
            {id: 550, name: "sqlmap --headers=[headers]", description: "Extra HTTP headers", category: "security"},
            {id: 551, name: "sqlmap --delay=[sec]", description: "Delay in seconds between requests", category: "security"},
            {id: 552, name: "sqlmap --timeout=[sec]", description: "Seconds to wait before timeout", category: "security"},
            {id: 553, name: "sqlmap --retries=[num]", description: "Retries when connection fails", category: "security"},
            {id: 554, name: "sqlmap --threads=[num]", description: "Max number of concurrent requests", category: "security"},
            {id: 555, name: "sqlmap --output-dir=[dir]", description: "Custom output directory", category: "security"},
            {id: 556, name: "sqlmap --dump-format=[format]", description: "Format of dumped data (CSV, HTML, SQLITE)", category: "security"},
            {id: 557, name: "sqlmap --eta", description: "Display for each output the estimated time", category: "security"},
            {id: 558, name: "sqlmap --flush-session", description: "Flush session files", category: "security"},
            {id: 559, name: "sqlmap --fresh-queries", description: "Ignore query results stored in session file", category: "security"},
            {id: 560, name: "sqlmap --hex", description: "Use hex conversion during data retrieval", category: "security"},
            {id: 561, name: "sqlmap --no-cast", description: "Turn off payload casting mechanism", category: "security"},
            {id: 562, name: "sqlmap --no-escape", description: "Turn off string escaping mechanism", category: "security"},
            {id: 563, name: "sqlmap --prefix=[prefix]", description: "Injection payload prefix string", category: "security"},
            {id: 564, name: "sqlmap --suffix=[suffix]", description: "Injection payload suffix string", category: "security"},
            {id: 565, name: "sqlmap --tamper=[script]", description: "Use given script(s) for tampering", category: "security"},
            {id: 566, name: "sqlmap --dbms=[dbms]", description: "Force back-end DBMS to provided value", category: "security"},
            {id: 567, name: "sqlmap --os=[os]", description: "Force back-end DBMS operating system", category: "security"},
            {id: 568, name: "sqlmap --invalid-bignum", description: "Use big numbers for invalidating values", category: "security"},
            {id: 569, name: "sqlmap --invalid-logical", description: "Use logical operations for invalidating values", category: "security"},
            {id: 570, name: "sqlmap --invalid-string", description: "Use random strings for invalidating values", category: "security"},
            {id: 571, name: "sqlmap --no-optimization", description: "Turn off optimization techniques", category: "security"},
            {id: 572, name: "sqlmap --no-escape", description: "Turn off string escaping mechanism", category: "security"},
            {id: 573, name: "sqlmap --hpp", description: "Use HTTP parameter pollution", category: "security"},
            {id: 574, name: "sqlmap --test-filter=[filter]", description: "Select tests by payloads and/or titles", category: "security"},
            {id: 575, name: "sqlmap --test-skip=[skip]", description: "Skip tests by payloads and/or titles", category: "security"},
            {id: 576, name: "sqlmap --csrf-token=[token]", description: "Parameter used to hold anti-CSRF token", category: "security"},
            {id: 577, name: "sqlmap --csrf-url=[url]", description: "URL address to visit for extraction of anti-CSRF token", category: "security"},
            {id: 578, name: "sqlmap --force-ssl", description: "Force usage of SSL/HTTPS", category: "security"},
            {id: 579, name: "sqlmap --chunked", description: "Use HTTP chunked transfer encoded", category: "security"},
            {id: 580, name: "sqlmap --hpp", description: "Use HTTP parameter pollution", category: "security"},
            {id: 581, name: "sqlmap --eval=[code]", description: "Evaluate provided Python code", category: "security"},
            {id: 582, name: "sqlmap --predict-output", description: "Predict common queries output", category: "security"},
            {id: 583, name: "sqlmap --keep-alive", description: "Use persistent HTTP(s) connections", category: "security"},
            {id: 584, name: "sqlmap --null-connection", description: "Retrieve page length without actual HTTP response body", category: "security"},
            {id: 585, name: "sqlmap --threads=[num]", description: "Max number of concurrent HTTP(s) requests", category: "security"},
            {id: 586, name: "sqlmap --time-sec=[sec]", description: "Seconds to delay the DBMS response", category: "security"},
            {id: 587, name: "sqlmap --union-cols=[cols]", description: "Range of columns to test for UNION query", category: "security"},
            {id: 588, name: "sqlmap --union-char=[char]", description: "Character to use for bruteforcing number of columns", category: "security"},
            {id: 589, name: "sqlmap --union-from=[table]", description: "Table to use in FROM part of UNION query", category: "security"},
            {id: 590, name: "sqlmap --dns-domain=[domain]", description: "Domain name used for DNS exfiltration attack", category: "security"},
            {id: 591, name: "sqlmap --second-url=[url]", description: "Resulting page URL searched for second-order response", category: "security"},
            {id: 592, name: "sqlmap --second-req=[file]", description: "Load second-order HTTP request from file", category: "security"},
            {id: 593, name: "sqlmap --technique=[tech]", description: "SQL injection techniques to use (B, E, U, S, T, Q)", category: "security"},
            {id: 594, name: "sqlmap --time-sec=[sec]", description: "Seconds to delay the DBMS response", category: "security"},
            {id: 595, name: "sqlmap --union-cols=[cols]", description: "Range of columns to test for UNION query", category: "security"},
            {id: 596, name: "sqlmap --union-char=[char]", description: "Character to use for bruteforcing number of columns", category: "security"},
            {id: 597, name: "sqlmap --union-from=[table]", description: "Table to use in FROM part of UNION query", category: "security"},
            {id: 598, name: "sqlmap --dns-domain=[domain]", description: "Domain name used for DNS exfiltration attack", category: "security"},
            {id: 599, name: "sqlmap --second-url=[url]", description: "Resulting page URL searched for second-order response", category: "security"},
            {id: 600, name: "sqlmap --second-req=[file]", description: "Load second-order HTTP request from file", category: "security"},

            // Utilities (100)
            {id: 601, name: "clear", description: "Clear terminal screen", category: "utils"},
            {id: 602, name: "reset", description: "Reset terminal", category: "utils"},
            {id: 603, name: "history", description: "Show command history", category: "utils"},
            {id: 604, name: "history -c", description: "Clear command history", category: "utils"},
            {id: 605, name: "!!", description: "Repeat last command", category: "utils"},
            {id: 606, name: "!n", description: "Execute nth command in history", category: "utils"},
            {id: 607, name: "!-n", description: "Execute command n lines back", category: "utils"},
            {id: 608, name: "!string", description: "Execute most recent command starting with string", category: "utils"},
            {id: 609, name: "!?string?", description: "Execute most recent command containing string", category: "utils"},
            {id: 610, name: "alias", description: "List aliases", category: "utils"},
            {id: 611, name: "alias name='command'", description: "Create alias", category: "utils"},
            {id: 612, name: "unalias name", description: "Remove alias", category: "utils"},
            {id: 613, name: "echo [text]", description: "Display text", category: "utils"},
            {id: 614, name: "echo $[var]", description: "Display variable value", category: "utils"},
            {id: 615, name: "printf [format] [args]", description: "Format and print data", category: "utils"},
            {id: 616, name: "yes [text]", description: "Repeat text indefinitely", category: "utils"},
            {id: 617, name: "seq [first] [last]", description: "Print sequence of numbers", category: "utils"},
            {id: 618, name: "seq [first] [incr] [last]", description: "Print sequence with increment", category: "utils"},
            {id: 619, name: "factor [number]", description: "Print prime factors", category: "utils"},
            {id: 620, name: "bc", description: "Arbitrary precision calculator", category: "utils"},
            {id: 621, name: "dc", description: "Reverse-polish desk calculator", category: "utils"},
            {id: 622, name: "expr [expression]", description: "Evaluate expression", category: "utils"},
            {id: 623, name: "let [expression]", description: "Evaluate arithmetic expression", category: "utils"},
            {id: 624, name: "test [expression]", description: "Check file types/compare values", category: "utils"},
            {id: 625, name: "[ [expression] ]", description: "Test alternative syntax", category: "utils"},
            {id: 626, name: "true", description: "Do nothing, successfully", category: "utils"},
            {id: 627, name: "false", description: "Do nothing, unsuccessfully", category: "utils"},
            {id: 628, name: "sleep [seconds]", description: "Delay for specified time", category: "utils"},
            {id: 629, name: "time [command]", description: "Time command execution", category: "utils"},
            {id: 630, name: "timeout [time] [command]", description: "Run command with time limit", category: "utils"},
            {id: 631, name: "watch [command]", description: "Execute program periodically", category: "utils"},
            {id: 632, name: "watch -n [sec] [command]", description: "Execute every n seconds", category: "utils"},
            {id: 633, name: "watch -d [command]", description: "Highlight differences", category: "utils"},
            {id: 634, name: "nohup [command]", description: "Run command immune to hangups", category: "utils"},
            {id: 635, name: "setsid [command]", description: "Run program in new session", category: "utils"},
            {id: 636, name: "disown", description: "Remove job from job table", category: "utils"},
            {id: 637, name: "wait [pid]", description: "Wait for process completion", category: "utils"},
            {id: 638, name: "fg", description: "Bring job to foreground", category: "utils"},
            {id: 639, name: "bg", description: "Send job to background", category: "utils"},
            {id: 640, name: "jobs", description: "List background jobs", category: "utils"},
            {id: 641, name: "kill %[job]", description: "Kill background job", category: "utils"},
            {id: 642, name: "suspend", description: "Suspend shell", category: "utils"},
            {id: 643, name: "exit", description: "Exit shell", category: "utils"},
            {id: 644, name: "logout", description: "Logout of shell", category: "utils"},
            {id: 645, name: "Ctrl+D", description: "Send EOF (often exits shell)", category: "utils"},
            {id: 646, name: "Ctrl+C", description: "Interrupt process", category: "utils"},
            {id: 647, name: "Ctrl+Z", description: "Suspend process", category: "utils"},
            {id: 648, name: "Ctrl+\\", description: "Quit process", category: "utils"},
            {id: 649, name: "Ctrl+S", description: "Stop output to screen", category: "utils"},
            {id: 650, name: "Ctrl+Q", description: "Resume output to screen", category: "utils"},
            {id: 651, name: "Ctrl+L", description: "Clear screen", category: "utils"},
            {id: 652, name: "Ctrl+R", description: "Search command history", category: "utils"},
            {id: 653, name: "Ctrl+G", description: "Abort history search", category: "utils"},
            {id: 654, name: "Ctrl+A", description: "Move to start of line", category: "utils"},
            {id: 655, name: "Ctrl+E", description: "Move to end of line", category: "utils"},
            {id: 656, name: "Ctrl+U", description: "Delete to start of line", category: "utils"},
            {id: 657, name: "Ctrl+K", description: "Delete to end of line", category: "utils"},
            {id: 658, name: "Ctrl+W", description: "Delete previous word", category: "utils"},
            {id: 659, name: "Ctrl+Y", description: "Paste deleted text", category: "utils"},
            {id: 660, name: "Ctrl+_", description: "Undo", category: "utils"},
            {id: 661, name: "Ctrl+X Ctrl+E", description: "Edit command in editor", category: "utils"},
            {id: 662, name: "Ctrl+X Ctrl+R", description: "Re-read init file", category: "utils"},
            {id: 663, name: "Ctrl+X Ctrl+U", description: "Undo all changes to line", category: "utils"},
            {id: 664, name: "Ctrl+X Ctrl+V", description: "Display version", category: "utils"},
            {id: 665, name: "Ctrl+X Ctrl+X", description: "Exchange point and mark", category: "utils"},
            {id: 666, name: "Ctrl+X *", description: "Glob complete", category: "utils"},
            {id: 667, name: "Ctrl+X G", description: "Glob list expansions", category: "utils"},
            {id: 668, name: "Ctrl+X P", description: "Display possible completions", category: "utils"},
            {id: 669, name: "Ctrl+X R", description: "Read init file", category: "utils"},
            {id: 670, name: "Ctrl+X U", description: "Undo all changes to line", category: "utils"},
            {id: 671, name: "Ctrl+X ]", description: "Character search forward", category: "utils"},
            {id: 672, name: "Ctrl+X [", description: "Character search backward", category: "utils"},
            {id: 673, name: "Ctrl+X Ctrl+E", description: "Edit command in editor", category: "utils"},
            {id: 674, name: "Ctrl+X Ctrl+R", description: "Re-read init file", category: "utils"},
            {id: 675, name: "Ctrl+X Ctrl+U", description: "Undo all changes to line", category: "utils"},
            {id: 676, name: "Ctrl+X Ctrl+V", description: "Display version", category: "utils"},
            {id: 677, name: "Ctrl+X Ctrl+X", description: "Exchange point and mark", category: "utils"},
            {id: 678, name: "Ctrl+X *", description: "Glob complete", category: "utils"},
            {id: 679, name: "Ctrl+X G", description: "Glob list expansions", category: "utils"},
            {id: 680, name: "Ctrl+X P", description: "Display possible completions", category: "utils"},
            {id: 681, name: "Ctrl+X R", description: "Read init file", category: "utils"},
            {id: 682, name: "Ctrl+X U", description: "Undo all changes to line", category: "utils"},
            {id: 683, name: "Ctrl+X ]", description: "Character search forward", category: "utils"},
            {id: 684, name: "Ctrl+X [", description: "Character search backward", category: "utils"},
            {id: 685, name: "Ctrl+X Ctrl+E", description: "Edit command in editor", category: "utils"},
            {id: 686, name: "Ctrl+X Ctrl+R", description: "Re-read init file", category: "utils"},
            {id: 687, name: "Ctrl+X Ctrl+U", description: "Undo all changes to line", category: "utils"},
            {id: 688, name: "Ctrl+X Ctrl+V", description: "Display version", category: "utils"},
            {id: 689, name: "Ctrl+X Ctrl+X", description: "Exchange point and mark", category: "utils"},
            {id: 690, name: "Ctrl+X *", description: "Glob complete", category: "utils"},
            {id: 691, name: "Ctrl+X G", description: "Glob list expansions", category: "utils"},
            {id: 692, name: "Ctrl+X P", description: "Display possible completions", category: "utils"},
            {id: 693, name: "Ctrl+X R", description: "Read init file", category: "utils"},
            {id: 694, name: "Ctrl+X U", description: "Undo all changes to line", category: "utils"},
            {id: 695, name: "Ctrl+X ]", description: "Character search forward", category: "utils"},
            {id: 696, name: "Ctrl+X [", description: "Character search backward", category: "utils"},
            {id: 697, name: "Ctrl+X Ctrl+E", description: "Edit command in editor", category: "utils"},
            {id: 698, name: "Ctrl+X Ctrl+R", description: "Re-read init file", category: "utils"},
            {id: 699, name: "Ctrl+X Ctrl+U", description: "Undo all changes to line", category: "utils"},
            {id: 700, name: "Ctrl+X Ctrl+V", description: "Display version", category: "utils"},

            // Additional commands to reach 1000+
            {id: 701, name: "pkg install termux-api", description: "Install Termux API", category: "package"},
            {id: 702, name: "termux-battery-status", description: "Check battery status", category: "utils"},
            {id: 703, name: "termux-camera-info", description: "Get camera information", category: "utils"},
            {id: 704, name: "termux-clipboard-get", description: "Get clipboard content", category: "utils"},
            {id: 705, name: "termux-clipboard-set", description: "Set clipboard content", category: "utils"},
            {id: 706, name: "termux-contact-list", description: "List contacts", category: "utils"},
            {id: 707, name: "termux-download [url]", description: "Download file", category: "utils"},
            {id: 708, name: "termux-fingerprint", description: "Use fingerprint sensor", category: "utils"},
            {id: 709, name: "termux-infrared-transmit [freq]", description: "Transmit IR frequency", category: "utils"},
            {id: 710, name: "termux-location", description: "Get device location", category: "utils"},
            {id: 711, name: "termux-notification --title [title] --content [content]", description: "Create notification", category: "utils"},
            {id: 712, name: "termux-sensor -l", description: "List sensors", category: "utils"},
            {id: 713, name: "termux-sensor -s [sensor]", description: "Get sensor data", category: "utils"},
            {id: 714, name: "termux-share [file]", description: "Share file"},
            {id: 715, name: "termux-sms-list", description: "List SMS messages", category: "utils"},
            {id: 716, name: "termux-sms-send -n [number] [message]", description: "Send SMS", category: "utils"},
            {id: 717, name: "termux-telephony-call [number]", description: "Make phone call", category: "utils"},
            {id: 718, name: "termux-telephony-cellinfo", description: "Get cell info", category: "utils"},
            {id: 719, name: "termux-telephony-deviceinfo", description: "Get device info", category: "utils"},
            {id: 720, name: "termux-toast [text]", description: "Show toast message", category: "utils"},
            {id: 721, name: "termux-torch on", description: "Turn on flashlight", category: "utils"},
            {id: 722, name: "termux-torch off", description: "Turn off flashlight", category: "utils"},
            {id: 723, name: "termux-tts-speak [text]", description: "Text to speech", category: "utils"},
            {id: 724, name: "termux-vibrate -d [ms]", description: "Vibrate for milliseconds", category: "utils"},
            {id: 725, name: "termux-volume [stream] [level]", description: "Set volume level", category: "utils"},
            {id: 726, name: "termux-wallpaper -f [file]", description: "Set wallpaper", category: "utils"},
            {id: 727, name: "termux-wifi-connectioninfo", description: "Get WiFi connection info", category: "utils"},
            {id: 728, name: "termux-wifi-enable true", description: "Enable WiFi", category: "utils"},
            {id: 729, name: "termux-wifi-enable false", description: "Disable WiFi", category: "utils"},
            {id: 730, name: "termux-wifi-scaninfo", description: "Scan WiFi networks", category: "utils"},
            {id: 731, name: "termux-open [file]", description: "Open file with default app", category: "utils"},
            {id: 732, name: "termux-open-url [url]", description: "Open URL in browser", category: "utils"},
            ];